INSERT INTO `Country` (`CountryName`) VALUES
('United States'),
('United Kingdom'),
('Canada'),
('Australia'),
('Algeria'),
('Brazil'),
('Belgium'),
('China'),
('Chile'),
('Colombia'),
('Czech Republic'),
('Denmark'),
('France'),
('Finland'),
('Greece'),
('India'),
('Italy'),
('Indonesia'),
('Iran'),
('Ireland'),
('Israel'),
('Japan'),
('Korea'),
('Malaysia'),
('Mexico'),
('Nigeria'),
('Netherlands'),
('Norway'),
('Pakistan'),
('Poland'),
('Romania'),
('Russia'),
('Spain'),
('Saudi Arabia'),
('South Africa'),
('Sweden'),
('Turkey'),
('Thailand'),
('Venezuela'),
('UAE');